version: '3'
services:
  api:
    build: hoteles-api
    ports:
     - "3000:3000"
    depends_on:
     - 'mongo'
    environment:
     - MONGO_CONN=mongodb://mongo:27017
  web:
    build: hoteles-ui
    ports:
     - "8080:8080"
    environment:
     - API_URL=http://localhost:3000/hoteles
  mongo:
    image: 'mongo:3.4.1'
    expose:
      - '27017'
    logging:
        driver: none